import { extractJsonObject } from "../local-ai/json.js";
import { getLocalAIStatus, localChat } from "../local-ai/index.js";
export type AnalystProvider = "local" | "rules";
/** Kept as an explicit local-only seam for callers; no provider keys are accepted. */
export interface AnalystEnv { localAi?: boolean; }
export interface LlmResult { data: Record<string, unknown>; provider: "local"; model: string; label: string; }
export interface CandidateStatus { id: string; provider: "local"; model: string; label: string; configured: boolean; available: boolean; reason: "ok" | "idle" | "error"; cooldownMs: number; lastError: string | null; lastOkAt: string | null; }
let lastError: string | null = null; let lastOkAt: number | null = null;
export async function routeLlmJson(prompt: string, _env: AnalystEnv): Promise<LlmResult | null> { const local = getLocalAIStatus(); if (local.state !== "ready") { lastError = local.error?.message ?? "Local model is not ready"; return null; } try { const text = await localChat([{ role: "system", content: "Return only valid JSON." }, { role: "user", content: prompt }], { json: true, maxTokens: 1000 }); const data = extractJsonObject(text); if (!data) throw new Error("local model returned invalid JSON"); lastError = null; lastOkAt = Date.now(); return { data, provider: "local", model: local.model?.id ?? "local", label: local.model?.label ?? "Local model" }; } catch (err) { lastError = (err as Error).message; return null; } }
export function getAnalystStatus(_env: AnalystEnv) { const local = getLocalAIStatus(); const candidate: CandidateStatus = { id: local.model?.id ?? "local", provider: "local", model: local.model?.id ?? "local", label: local.model?.label ?? "Local model", configured: Boolean(local.model && local.runtime), available: local.state === "ready", reason: lastError ? "error" : local.state === "ready" ? "ok" : "idle", cooldownMs: 0, lastError, lastOkAt: lastOkAt ? new Date(lastOkAt).toISOString() : null }; return { candidates: [candidate], configuredCount: candidate.configured ? 1 : 0, availableCount: candidate.available ? 1 : 0 }; }
